# Generated by Django 2.2 on 2019-12-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidTableModel',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('bdate', models.DateField(auto_now_add=True)),
                ('btime', models.TimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ProductModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
    ]
